[package]
name = "esp-rs-copro"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0 OR MIT"

[profile.release]
panic = 'abort'

[package.metadata.docs.rs]
features = ["is-lp-core", "has-lp-core", "esp32c6", "esp32s3", "move_on_need"]

[dependencies]
esp-println = { workspace = true, optional = true }
esp-lp-hal = { workspace = true, optional = true }
esp-hal = { workspace = true, optional = true }
esp-sync = { workspace = true, optional = true }
embassy-sync-06 = { package = "embassy-sync", version = "0.6", optional = true }
embassy-sync-07 = { package = "embassy-sync", version = "0.7", optional = true }
embassy-sync-08 = { package = "embassy-sync", version = "0.8", optional = true }
riscv = { version = ">=0.15.0", optional = true }

[dev-dependencies]
esp-rs-copro-procmacro = { path = "../esp-rs-copro-procmacro", features=[] }
rand = "0.10.0"

[features]
default = []
nottest = []
is-lp-core = ["dep:esp-lp-hal", "nottest"]
has-lp-core = ["dep:esp-println", "dep:esp-hal", "dep:esp-sync", "dep:embassy-sync-06", "dep:embassy-sync-07", "dep:embassy-sync-08", "nottest"]
esp32c6 = ["esp-lp-hal?/esp32c6", "esp-hal?/esp32c6", "esp-println?/esp32c6", "esp-sync?/esp32c6", "dep:riscv"]
esp32s3 = ["esp-lp-hal?/esp32s3", "esp-hal?/esp32s3", "esp-println?/esp32s3", "esp-sync?/esp32s3"]
custom_range = []
move_on_need = []
